modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "GPL-3.0"

[[mods]]
modId = "apatheticmobsreborn"
version = "${version}"
displayName = "Apathetic Mobs Reborn"
authors = "embeddedt"
description = '''
A reinvention of Apathetic Mobs for Minecraft 1.16+.
'''
#logoFile = ""

[[dependencies.apatheticmobsreborn]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.apatheticmobsreborn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.apatheticmobsreborn]]
modId = "cloth_config"
mandatory = true
versionRange = "[4.11.26,)"
ordering = "NONE"
side = "BOTH"
